FROM python:3.11.4-slim

ENV PYTHONUNBUFFERED 1
ENV DOCKER 1
ENV AIRFLOW_HOME /app

# Setup for psycopg2-binary and make
RUN apt-get update && apt-get install -y apt-utils libpq-dev python3-dev git vim make wget gcc build-essential

WORKDIR /app

# Application Environment
ADD requirements.txt ./
ADD airflow.cfg ./

RUN pip install --upgrade pip
RUN pip install psycopg2
RUN pip install -r requirements.txt

ADD . .
